xgds_notes2/urls.py
#__BEGIN_LICENSE__
# Copyright (c) 2015, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All rights reserved.
#
# The xGDS platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#__END_LICENSE__

from django.conf.urls import url, include
from django.conf import settings

import xgds_notes2.views as views


urlpatterns = [
    url(r'^record/?$', views.record, {}, 'xgds_notes_record'),
    url(r'^recordSimple/?$', views.recordSimple, {}, 'record_simple'),
    url(r'^editNote/(?P<note_pk>[\d]+)$', views.editNote, {}, 'xgds_notes_edit_note'),
    url(r'^record/session/?$', views.editUserSession, {}, 'xgds_notes_edit_user_session'),
    url(r'^record/session/ajax/?$', views.editUserSession, {'ajax':True}, 'xgds_notes_edit_user_session_ajax'),
    url(r'^editTags/?$', views.editTags, {}, 'xgds_notes_edit_tags'),
    url(r'^addRootTag/?$', views.addRootTag, {}, 'xgds_notes_add_root_tag'),
    url(r'^addTag/?$', views.addTag, {}, 'xgds_notes_add_tag'),
    url(r'^moveTag/?$', views.moveTag, {}, 'xgds_notes_move_tag'),
    url(r'^makeRoot/(?P<tag_id>[\d]+)$', views.makeRootTag, {}, 'xgds_notes_move_tag'),
    url(r'^editTag/(?P<tag_id>[\d]+)$', views.editTag, {}, 'xgds_notes_edit_tag'),
    url(r'^deleteTag/(?P<tag_id>[\d]+)$', views.deleteTag, {}, 'xgds_notes_delete_tag'),
    url(r'^import/?$', views.importNotes, {}, 'xgds_notes_import'),
    url(r'^searchMap$', views.notesSearchMap, {}, 'search_xgds_notes_map'),
    url(r'^searchMap/(?P<filter>(([\w]+|[a-zA-Z0-9:._\-\s]+),*)+)$', views.notesSearchMap, {}, 'search_xgds_notes_map_filter'),

    # Including these in this order ensures that reverse will return the non-rest urls for use in our server
    url(r'^rest/', include('xgds_notes2.restUrls')),
    url('', include('xgds_notes2.restUrls')),

    ]


if False and settings.XGDS_SSE:
    from sse_wrapper.views import EventStreamView
    urlpatterns += [
        url(r'^live/notes/(?P<filter>[\w]+:[\w]+)/$', views.getNotesJson, {}, 'xgds_notes_liveNotes'),
        url(r'^live/notes-stream/(?P<channel_extension>[\w]+:[\w]+)/$', EventStreamView.as_view(channel='live/notes'), {}, 'xgds_notes_liveNotes_stream'),

        url(r'^live/notes/$', views.getNotesJson, {}, 'xgds_notes_liveNotes'),
        url(r'^live/notes-stream/$', EventStreamView.as_view(channel='live/notes'), {}, 'xgds_notes_liveNotes_stream'),
        ]

xgds_notes2/forms.py
#__BEGIN_LICENSE__
# Copyright (c) 2015, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All rights reserved.
#
# The xGDS platform is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#__END_LICENSE__

import cgi
import datetime
import pytz

# from haystack.query import SearchQuerySet
from django import forms
from django.conf import settings
from django.utils.functional import lazy
from django.db.models import Q
from dateutil.parser import parse as dateparser

from dal import autocomplete

from geocamUtil.extFileField import ExtFileField
from geocamUtil.forms.AbstractImportForm import getTimezoneChoices
from geocamUtil.loader import LazyGetModelByName
from taggit.forms import *
from xgds_core.models import XgdsUser
from xgds_core.forms import SearchForm, AbstractImportVehicleForm

from xgds_map_server.models import Place
from xgds_map_server.forms import buildQueryForPlace
from xgds_notes2.models import Role, Location, HierarchichalTag
from xgds_notes2.utils import buildQueryForTags

NOTE_MODEL = LazyGetModelByName(settings.XGDS_NOTES_NOTE_MODEL)
MESSAGE_MODEL = LazyGetModelByName(settings.XGDS_NOTES_MESSAGE_MODEL)
USER_SESSION_MODEL = LazyGetModelByName(settings.XGDS_NOTES_USER_SESSION_MODEL)
TAG_MODEL = LazyGetModelByName(settings.XGDS_NOTES_TAG_MODEL)

PLACE_FILTER_URL = '/xgds_core/complete/%s.json/' % 'xgds_map_server.Place'


class UserSessionForm(forms.ModelForm):
    class Meta:
        model = USER_SESSION_MODEL.get()
        fields = USER_SESSION_MODEL.get().getFormFields()


class NoteForm(forms.ModelForm):
    tags = TagField(required=False,
                    widget=TagWidget(attrs={'class': 'taginput', 
                                            'data-role':'tagsinput',
                                            'placeholder': 'Choose tags'}))

    note_submit_url = forms.CharField(widget=forms.HiddenInput(), initial='/notes/recordSimple/',  required=False)
    
    event_time = forms.DateTimeField(input_formats=settings.XGDS_CORE_DATE_FORMATS, required=False)
    event_timezone = forms.CharField(widget=forms.HiddenInput(), required=False)
    extras = forms.CharField(widget=forms.HiddenInput(), required=False)

    # for generic foreign key use
    app_label = forms.CharField(widget=forms.HiddenInput(), required=False)
    model_type = forms.CharField(widget=forms.HiddenInput(), required=False)
    object_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    position_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    # populate the event time with NOW if it is blank.
    def clean_event_time(self):
        etime = self.cleaned_data['event_time']
        if not etime:
            rightnow = datetime.datetime.now(pytz.utc)
            return rightnow
        return etime.replace(tzinfo=pytz.utc)
    
    def clean_content(self):
        text = self.cleaned_data['content']
        return cgi.escape(text)

    def __unicode__(self):
        return self.as_fieldsets()
    
    class Meta:
        model = NOTE_MODEL.get()
        fields = NOTE_MODEL.get().getFormFields()


class TagForm(forms.ModelForm):
    class Meta:
        model = TAG_MODEL.get()
        fields = TAG_MODEL.get().getFormFields()


class ImportNotesForm(AbstractImportVehicleForm):
    sourceFile = ExtFileField(ext_whitelist=(".csv", ), required=True)


class SearchMessageForm(SearchForm):

    min_event_time = forms.DateTimeField(input_formats=settings.XGDS_CORE_DATE_FORMATS, required=False,
                                         label='Min Time',
                                         widget=forms.DateTimeInput(attrs={'class': 'datetimepicker'}))
    max_event_time = forms.DateTimeField(input_formats=settings.XGDS_CORE_DATE_FORMATS, required=False,
                                         label='Max Time',
                                         widget=forms.DateTimeInput(attrs={'class': 'datetimepicker'}))

    event_timezone = forms.ChoiceField(required=False, choices=lazy(getTimezoneChoices, list)(empty=True),
                                       label='Time Zone', help_text='Required for Min/Max Time')

    author = forms.ModelChoiceField(XgdsUser.objects.all(),
                                    required=False,
                                    widget=autocomplete.ModelSelect2(url='select2_model_user'))

    field_order = MESSAGE_MODEL.get().getSearchFieldOrder()

    # populate the times properly
    def clean_min_event_time(self):
        return self.clean_time('min_event_time', self.clean_event_timezone())

    # populate the times properly
    def clean_max_event_time(self):
        return self.clean_time('max_event_time', self.clean_event_timezone())

    def clean_event_timezone(self):
        if self.cleaned_data['event_timezone'] == 'utc':
            return 'Etc/UTC'
        else:
            return self.cleaned_data['event_timezone']
        return None

    def clean_content(self):
        text = self.cleaned_data['content']
        return cgi.escape(text)

    def clean(self):
        cleaned_data = super(SearchMessageForm, self).clean()
        event_timezone = cleaned_data.get("event_timezone")
        min_event_time = cleaned_data.get("min_event_time")
        max_event_time = cleaned_data.get("max_event_time")

        if max_event_time or min_event_time:
            if not event_timezone:
                self.add_error('event_timezone', "Time Zone is required for min / max times.")
                raise forms.ValidationError(
                    "Time Zone is required for min / max times."
                )
            else:
                del cleaned_data["event_timezone"]

    def buildQueryForField(self, fieldname, field, value, minimum=False, maximum=False):
        # TODO if fieldname is content, then call sphinx

        if fieldname == 'content':
            return self.buildContainsQuery(fieldname, field, value)
        return super(SearchMessageForm, self).buildQueryForField(fieldname, field, value, minimum, maximum)

    class Meta:
        model = MESSAGE_MODEL.get()
        fields = MESSAGE_MODEL.get().getSearchFormFields()


class SearchNoteForm(SearchMessageForm):
    hierarchy = forms.BooleanField(required=False, label='Include tag descendants')
    tags = TagField(required=False,
                    widget=TagWidget(attrs={'class': 'taginput', 
                                            'data-role':'tagsinput',
                                            'placeholder': 'Choose tags'}))
    
    role = forms.ModelChoiceField(required=False, queryset=Role.objects.all())
    location = forms.ModelChoiceField(required=False, queryset=Location.objects.all())

    place_hierarchy = forms.BooleanField(required=False, label='Include %s descendants' % settings.XGDS_MAP_SERVER_PLACE_MONIKER)

    place = forms.ModelChoiceField(Place.objects.all(),
                                   label=settings.XGDS_MAP_SERVER_PLACE_MONIKER,
                                   required=False,
                                   widget=autocomplete.ModelSelect2(url=PLACE_FILTER_URL))

    field_order = NOTE_MODEL.get().getSearchFieldOrder()
    
    def buildQueryForField(self, fieldname, field, value, minimum=False, maximum=False):
        # for hierarchichal search or tags, do custom
        # otherwise fall back to base method
        # if fieldname is content, then call sphinx

        if fieldname == 'tags':
            hierarchy = self.cleaned_data['hierarchy']
            return buildQueryForTags(fieldname, field, value, hierarchy)
        if fieldname == 'place':
            place_hierarchy = self.cleaned_data['place_hierarchy']
            return buildQueryForPlace(fieldname, field, value, place_hierarchy)
        elif fieldname == 'hierarchy' or fieldname == 'place_hierarchy':
            return None
        elif fieldname == 'content':
            return self.buildContainsQuery(fieldname, field, value)
        return super(SearchNoteForm, self).buildQueryForField(fieldname, field, value, minimum, maximum)

    class Meta:
        model = NOTE_MODEL.get()
        fields = NOTE_MODEL.get().getSearchFormFields()

xgds_notes2/templates/xgds_notes2/NoteCSS.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{{ EXTERNAL_URL }}bootstrap-tagsinput/dist/bootstrap-tagsinput.css"></link>
{% include "xgds_notes2/NoteTableCSS.html" %}
<link rel="stylesheet" type="text/css" href="{% static 'xgds_notes2/css/tags_input.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'xgds_notes2/css/note_input_form_small.css' %}"></link>
<link rel="stylesheet" type="text/css" href="{% static 'xgds_notes2/css/note_table.css' %}"></link>

xgds_notes2/templates/xgds_notes2/NoteJS.html
{% load static %}
<script type="text/javascript">
	    server_time_url = "{% url 'server_time' %}";
		user_session_exists = false;
		// global name of a Note
		note_model_name = "{{ settings.XGDS_NOTES_MODEL_NAME }}";
</script>
{% include "xgds_core/timeJS.html" %}
<!--  TODO remove the below 2 lines once we switch to bootstrap -->
<script src="{{ EXTERNAL_URL }}tether/dist/js/tether.min.js"></script>
<script type="text/javascript" src="{{ EXTERNAL_URL }}bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{{ EXTERNAL_URL }}typeahead.js/dist/typeahead.bundle.min.js"></script> 
<script type="text/javascript" src="{{ EXTERNAL_URL }}bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>
{% include "xgds_notes2/NoteTableJS.html" %}
<script type="text/javascript" src="{% static 'xgds_notes2/js/tags_input.js' %}"></script>
<script type="text/javascript" src="{% static 'xgds_notes2/js/note_create_form.js' %}"></script>
<script type="text/javascript" src="{% static 'xgds_notes2/js/note_table.js' %}"></script>

{% if user.is_authenticated %}
 {% if forceUserSession or not request.session.notes_user_session %}
 	{% load user_session_popup %}
 	{% show_user_session_popup %}
 {% else %}
 	<script type="text/javascript">
 		// user is already authenticated
 		user_session_exists = true;
 	</script>
 {% endif %}
{% endif %}

<script type="text/javascript" src="{% static 'xgds_notes2/js/note_input_form_small.js' %}"></script>

xgds_notes2/templates/xgds_notes2/NoteTableCSS.html
{% if settings.GEOCAM_UTIL_DATATABLES_EDITOR %}
<link rel="stylesheet" type="text/css" href="{{ EXTERNAL_URL }}datatables-editor/css/editor.dataTables.css"></link>
<link rel="stylesheet" type="text/css" href="{{ EXTERNAL_URL }}datatables-editor/css/editor.jqueryui.min.css"></link>
{% endif %}

xgds_notes2/templates/xgds_notes2/NoteTableJS.html
{% load static %}
	<script type="text/javascript" src="{{ EXTERNAL_URL }}datatables/media/js/jquery.dataTables.js"></script>
	<script type="text/javascript" src="{{ EXTERNAL_URL }}datatables.net-select/js/dataTables.select.min.js"></script>
	{% if settings.GEOCAM_UTIL_DATATABLES_EDITOR %}
  		<script type="text/javascript" src="{{ EXTERNAL_URL }}datatables-editor/js/dataTables.editor.js"></script>
  		<script type="text/javascript" src="{% static 'xgds_notes2/js/dataTables.editor.tagsinput.js' %}"></script>
  		<script type="text/javascript">
  		HAS_DATATABLES_EDITOR = true;
  		</script>
  	{% else %}
  		<script type="text/javascript">
  		HAS_DATATABLES_EDITOR = false;
  		</script>
  	{% endif %}
  	<script type="text/javascript" src="{{ EXTERNAL_URL }}datatables.net-plugins/sorting/datetime-moment.js"></script>

xgds_notes2/templates/xgds_notes2/add_root_tag.html
{% extends "xgds_notes2/notes_base.html" %}

{% block content %}
<h4>Add Root Tag</h4>
<form id="xgds_notes_add_root_tag" action="{% url 'xgds_notes_add_root_tag' %}" method="post">
	<table>
    {{ form.as_table }}
    </table>
    <div id="buttons" >
        <input id="save_tag" class="btn btn-primary" type="submit" value="Save">
    </div>
</form>
{% endblock content %}

xgds_notes2/templates/xgds_notes2/map_record_notes.html
{% extends 'xgds_map_server/mapSearch.html' %}
{% load static %}

{% block sitemenu-content-secondary %}
	{% include "xgds_map_server/mapSearch_subnav.html" %}
{% endblock %}

{% block siteSection %}Notes{% endblock %}

{% block scripts %}
	{{block.super}}
    <script type="text/javascript" src="{% static 'xgds_notes2/js/note_create_form.js' %}"></script>
{% endblock scripts %}
{% block postscripts %}
{% endblock postscripts %}

{% block buttonrowLeft %}
<div id="full_notesDiv">
	<div id="notes_content" class="notes_content mb-2">
		{% include 'xgds_notes2/notes_input_include_full.html' %}
 	</div>
 </div>
{% endblock buttonrowLeft %}

{% block otherJSInit %}
server_time_url = "{% url 'server_time' %}";
serverTimezone = "{{TIME_ZONE}}";

{% block initializeNotes %}
var container = $("#full_notes_input");
xgds_notes.setupNotesUI(container);
xgds_notes.initializeNotesForm(false);
{% endblock initializeNotes %}

{% block eventTimeFunction %}
xgds_notes.getEventTime = function(context) {
		var dataString = "";
		var parent = $(context).closest('.notes_input_container');
	    var event_hidden = parent.find('#id_event_time');
	    if (event_hidden.length == 0){
	    	event_hidden = $("#id_event_time");
	    }
	    var event_timestring = event_hidden.val();
	    
	    try {
	        if (event_timestring !== undefined && event_timestring !== ""){
	        	if (!event_hidden.is(':visible')){ // in a form
		            dataString = dataString + '&event_time=' + event_timestring;
		            try {
		            	var timezone_hidden = parent.find('#id_event_timezone');
		            	dataString = dataString + "&event_timezone=" + timezone_hidden.val();
		            } catch(err){
		            	// no timezone
		            }
			    } else {
		        	var tzified = getUTCTime(event_timestring.substring(0, event_timestring.length-4), serverTimezone);
					var theUtc = tzified.utc().format('YYYY/MM/DD HH:mm:ss') + ' UTC';
		            dataString = dataString + '&event_time=' + theUtc;
		            try {
		            	dataString = dataString + "&event_timezone=" + serverTimezone;
		            } catch(err){
		            	// no timezone
		            }
		        }
	        } else {
	        	if (event_hidden.is(':visible')){
		            dataString = dataString + "&serverNow=true";
		        }
	        }
	    }
	    catch(err) {
	        dataString = dataString + "&serverNow=true";
	    }
	    return dataString;
	
	};
xgds_notes.postSubmit = function(data) {
   xgds_notes.clear_event_time();
};
{% endblock eventTimeFunction %}

{% block cleanDataFunction %}
xgds_notes.cleanData = function(data, containerDiv){
	var fnc = containerDiv.closest('#full_notes_content');
	if (fnc.length > 0){
		// this line uses the `note_model_name` global variable defined in `NoteJS.html`
		var columns = app.options.searchModels[note_model_name].columns;
		result = [];
		for (var i=0; i < columns.length; i++) {
			result.push(data[columns[i]]);
		}
		return result;
	}
	return data;
}
{% endblock cleanDataFunction %}
xgds_notes.updateRole = function(stuff) {
	var theForm = $("#edit_user_session_form");
	var content = theForm.find("#id_location option:selected").text();
	if (content == '---------'){
		theForm.find("#id_location option[value='{{request.session.notes_user_session.location}}']").attr('selected', 'selected');
		theForm.find("#id_vehicle option[value='{{request.session.notes_user_session.vehicle}}']").attr('selected', 'selected');
		theForm.find("#id_role option[value='{{request.session.notes_user_session.role}}']").attr('selected', 'selected');
		var content = theForm.find("#id_location option:selected").text();
	} 
	content += ', ' + theForm.find("#id_vehicle option:selected").text();
	content += ', ' + theForm.find("#id_role option:selected").text();
	$("#roleLocationVehicle").text(content);
	if (content.indexOf('--') == -1){
		user_session_exists = true;
	}
}

$("#changeRole").click(function(e){
	xgds_notes.editUserSession('xgds_notes.updateRole');
});

xgds_notes.updateRole();

{% if settings.GEOCAM_UTIL_DATATABLES_EDITOR %}
xgds_notes.setupEditingTable = function() {
		if (app.searchResultsView !== undefined){
	        var _editor = new $.fn.dataTable.Editor( {
	        	ajax: '/notes/editNote/_id_',
	            table: '#searchResultsTable', 
	            idSrc:  22,
	            fields: app.searchResultsView.editableColumns
	        });
	        
	        var _this = this;
	        var mmap = app.searchResultsView.lookupModelMap('{{ settings.XGDS_NOTES_NOTE_MONIKER }}');
	        $('#searchResultsTable').on( 'dblclick', 'tbody td.editable', function (e) {
	        	var col = e.currentTarget._DT_CellIndex.column;
	        	var col_name = mmap.columns[col];
	            _editor.inline( this, col_name );
	        });
	     }
};
xgds_notes.setupEditingTable();

{% endif %}

 var input_initialized = false;
 app.vent.on('searchDiv:visible', function(){
 	if (!input_initialized){
 		var formNote = $("#form-Note");
 		var input = formNote.find('.taginput');
        xgds_notes.initializeInput(input);
        var role = formNote.find("#id_role");
        role.val(role.find("option:first").val());
        var location = formNote.find("#id_location");
        location.val(location.find("option:first").val());
        input_initialized = true;
 	} 
 });
{% endblock otherJSInit %}

xgds_notes2/templates/xgds_notes2/notes_base.html
{% extends "base.html" %}

{% block cssExtras %}
<link rel="stylesheet" type="text/css" href="{{ EXTERNAL_URL }}jquery-ui-dist/jquery-ui.min.css" ></link>
{% include "xgds_notes2/NoteCSS.html" %}
{% endblock cssExtras %}

{% block sitemenu-content-secondary %}
	{% include "xgds_notes2/notes_subnav.html" %}
{% endblock %}
	
{% block scripts %}
{{ block.super }}
<script language="javascript" type="text/javascript" src="{{ EXTERNAL_URL }}jquery-ui-dist/jquery-ui.min.js"></script>
{% include "xgds_notes2/NoteJS.html" %}
{% endblock scripts %}

xgds_notes2/templates/xgds_notes2/notes_input_include.html
{% if user.is_authenticated %}
<button id="add_note_button" class="btn btn-primary float_button add_note_button">+ Note</button>
<div id="notes_content" class="tab-content active notes_content notes_input_container">
	<div class="notediv" id="notes_input" style="display:none;">
		<form id="create_note" class="create_note_form" action="" method="POST">
			<input type="hidden" id="id_note_submit_url" value="{% url 'record_simple' %}">
			<input type="hidden" id="id_event_time" >
			<input type="hidden" id="id_event_timezone" >
			<input type="hidden" id="id_app_label" >
			<input type="hidden" id="id_model_type" >
			<input type="hidden" id="id_object_id" >
			<input type="hidden" id="id_position_id" >
			<div id="error_div" class="noteerrordiv">
				<span id="error_icon">&nbsp;</span>
				<span id="error_content"></span>
			</div>
			<div class="notecontainer" >
				<textarea class="noteinput"  id="id_content" type="text" name="content" maxlength="500" placeholder="Enter notes here"></textarea>
		        <input class="taginput"  id="id_tags" placeholder="Choose tags" type="text" />
		        <input id="save_note" type="submit" value="Save" class="btn btn-primary noteSubmit">
	        </div>
	  </form>
	</div>
</div>
{% endif %}

xgds_notes2/templates/xgds_notes2/notes_input_include_full.html
{% if user.is_authenticated %}
    <style type="text/css" >
    .checkbox-left-bla {
        width: auto;
        box-shadow: none;
    }
    .noteinput {
        min-height: 30px;
        width: 100%;
        min-width: 465px;
        height: 50px;
    }
    .you-are-alert {
        margin-left:-15px;
        margin-right:-15px;
    }
    .event-time {
        min-width: 150px;
    }
    </style>
<div id="full_notes_input">
    <button id="add_note_button" role="button" class="btn btn-primary add_note_button ml-2 mt-1 mr-1" style="color:white; max-height:1.8rem;">+ {{settings.XGDS_NOTES_NOTE_MONIKER}}</button>
    <div id="add_note_modal" class="modal hide fade notes_content" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Add {{settings.XGDS_NOTES_NOTE_MONIKER}}</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
                   <div class="modal-body mt-0 pt-0">
                            <div id="full_notes_content" >
                                <div class="notediv notes_input_container" id="notes_input" >

                                    <form id="create_note" class="create_note_form" action="" method="POST">
                                    <div class="container mt-0 pt-0" >
                                        <div id="error_div" class="row noteerrordiv mt-1">
                                            <span id="error_icon">&nbsp;</span>
                                            <span id="error_content" style="font-size:1.0em; padding-bottom:0px;" class="success small"></span>
                                        </div>
                                        <div class="alert alert-info mb-0 you-are-alert" role="alert">
                                            <div class="row">You are {{ user.first_name }} (<span id="roleLocationVehicle"></span>)
                                            </div>
                                            <div class="row">
                                                <a href="#" id="changeRole" class="font-italic" >change role/location</a>
                                            </div>
                                        </div>
                                        <input type="hidden" id="id_note_submit_url" value="{% url 'xgds_notes_record' %}">
                                        <input type="hidden" id="id_event_timezone" >
                                        <input type="hidden" id="id_app_label" >
                                        <input type="hidden" id="id_model_type" >
                                        <input type="hidden" id="id_object_id" >
                                        <input type="hidden" id="id_position_id" >

                                            <div class="row mt-1" id="event_time_controls2">
                                                <input id="id_event_time" name="event_time" class="event-time mr-1" type="text" style="display: inline-block;" placeholder="time">
                                                <button name="Now" id="nowButton" class="btn btn-primary mt-1">Now</button>
                                            </div>
                                            <div class="row mt-1">
                                                <textarea class="noteinput" id="id_content" type="text" name="content" maxlength="500" placeholder="Enter content here"></textarea>
                                            </div>
                                            <div class="row mt-1">
                                                <input class="taginput"  id="id_tags" placeholder="Choose tags" type="text" />
                                            </div>

                                            <div class="row mt-1 justify-content-start">
                                                <div class='col-sm-6' style="margin-left:-15px;">

                                                    {% if settings.XGDS_NOTES_SHOW_ON_MAP_CHECKBOX %}
                                                    <input id="id_show_on_map" name="show_on_map" type="checkbox" class="form-control pull-left mr-1">Show in GE</input><br/>
                                                    {% endif %}
                                                    <input id="id_keep_tags" name="keep_tags" type="checkbox" class="form-control pull-left mr-1" >Don't clear tags</input>
                                                </div>
                                            </div>
                                            <div class="row mt-1">

                                                <div class="d-flex justify-content-end">
                                                    <input id="save_note" type="submit" value="Save" class="btn btn-primary noteSubmit mr-1"><br/>
                                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                                                </div>
                                            </div>


                                        </div>
                                  </form>
                                </div>
                        </div>
                   </div>

            </div>
        </div>
    </div>
</div>
{% endif %}

xgds_notes2/templates/xgds_notes2/notes_table_small.html
<table id="notes_list" class="notes_list display table-striped" width="100%">
</table>